dotfiles: add zsh completion for dotfiles command

diff --git a/install b/install
--- a/install
+++ b/install
@@ -62,6 +62,7 @@ backups_base="${dotfiles_base_dir}/backups/backup-$(date "+%Y-%m-%d-%H%M%S")"
 no_copies=0
 no_links=0
 no_backups=0
+do_install=0
 do_settings=0
 
 ## Handle Dotfiles
@@ -214,7 +215,17 @@ while :; do
             no_backups=1
             shift
             ;;
+        install)
+            do_install=1
+            shift
+            ;;
         settings)
+            if [ "$do_install" = "1" ]; then
+                printf 'Cannot install and run settings simultaneously\n'
+                print_help >&2
+                exit 1
+            fi
+
             do_settings=1
             shift
             break
@@ -240,7 +251,7 @@ while :; do
     esac
 done
 
-if [ "$do_settings" = "1" ]; then
+if [ "$do_install" = "0" ] && [ "$do_settings" = "1" ]; then
     run_settings_file "$1"
     exit $?
 fi
