Add some safety checks to dotfiles install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,7 @@
 ## Helper functions
 
 clean_path() (
-    printf '%s' "$1" | sed "s/\/\{2,\}/\//g"
+    printf '%s' "$1" | sed "s/\\/\\{2,\\}/\\//g"
 )
 
 join_path() (
@@ -50,13 +50,13 @@ strip_trailing_slashes() (
 
 ## Variables
 
-script_name=$(basename "$0")
+script_name="$(basename "$0")"
 
 # Set base dir as the directory of this script
-dotfiles_base_dir=$(cd "$(dirname "$0")" && pwd -L)
-settings_dir=$(join_path "${dotfiles_base_dir}" "settings")
-dotfiles_dir=$(join_path "${dotfiles_base_dir}" "files")
-backups_base=${dotfiles_base_dir}/backups/backup-$(date "+%Y-%m-%d-%H%M%S")
+dotfiles_base_dir="$(cd "$(dirname "$0")" && pwd -L)"
+settings_dir="$(join_path "${dotfiles_base_dir}" "settings")"
+dotfiles_dir="$(join_path "${dotfiles_base_dir}" "files")"
+backups_base="${dotfiles_base_dir}/backups/backup-$(date "+%Y-%m-%d-%H%M%S")"
 
 # Set option defaults
 no_copies=0
@@ -65,6 +65,16 @@ no_backups=0
 do_settings=0
 
 ## Handle Dotfiles
+
+if [ -z "$script_name" ]; then
+    printf "%s\\n" "Could not determine script name. Exiting..."
+    exit 1
+fi
+
+if [ -z "${dotfiles_base_dir#/}" ]; then
+    printf "%s\\n" "Dotfiles base dir was empty or /. Exiting..."
+    exit 1
+fi
 
 backup_original() (
     _src=${1:?"No source path given"}
@@ -90,7 +100,7 @@ mk_dest_dir() (
     # Attempt to create the directory in case it doesn't exist
     mkdir -p "$_path"
 
-    printf "Created directory %s\n" "$(highlight_str "~${_path#${HOME}}")"
+    printf "Created directory %s\\n" "$(highlight_str "~${_path#${HOME}}")"
 )
 
 copy_path() (
