Add settings helper

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,21 +2,21 @@
 
 ## Helper functions
 
-clean_path() {
+clean_path() (
     printf '%s' "$1" | sed "s/\/\{2,\}/\//g"
-}
+)
 
-join_path() {
+join_path() (
     clean_path "$(printf '/%s' "$@")"
-}
+)
 
-get_extension() {
+get_extension() (
     printf '%s' "${1##*.}"
-}
+)
 
-highlight_str() {
+highlight_str() (
     printf '\033[4;32m%s\033[0m' "$1"
-}
+)
 
 success_message() (
     _action=${1:?}
@@ -27,7 +27,7 @@ success_message() (
 )
 
 # Adds a trailing slash to a path if it's a directory
-ensure_trailing_slash() {
+ensure_trailing_slash() (
     df_path="$1"
     if [ -d "$df_path" ]; then
         while [ "${df_path%/}" != "$df_path" ]; do
@@ -37,7 +37,7 @@ ensure_trailing_slash() {
     else
         printf '%s' "$df_path"
     fi
-}
+    )
 
 ## Variables
 
@@ -45,6 +45,7 @@ script_name=$(basename "$0")
 
 # Set base dir as the directory of this script
 dotfiles_base_dir=$(cd "$(dirname "$0")" && pwd -L)
+settings_dir=$(join_path "${dotfiles_base_dir}" "settings")
 dotfiles_dir=$(join_path "${dotfiles_base_dir}" "files")
 backups_base=${dotfiles_base_dir}/backups/backup-$(date "+%Y-%m-%d-%H%M%S")
 
@@ -52,8 +53,9 @@ backups_base=${dotfiles_base_dir}/backups/backup-$(date "+%Y-%m-%d-%H%M%S")
 no_copies=0
 no_links=0
 no_backups=0
+do_settings=0
 
-## Main Functions
+## Handle Dotfiles
 
 backup_original() (
     _src=${1:?"No source path given"}
@@ -145,6 +147,23 @@ install_dotfiles() (
     done
 )
 
+## Handle Settings
+
+run_settings_file() (
+    settings_file_path="$(join_path "$settings_dir" "$1")"
+    if [ -z "$1" ]; then
+        echo "Error: no settings file name specified"
+        exit 1
+    fi
+
+    if [ ! -f "$settings_file_path" ]; then
+        echo "Error: Setting \"$1\" does not exist"
+        exit 1
+    fi
+
+    . "$settings_file_path"
+)
+
 ## Main
 
 print_help() {
@@ -176,6 +195,11 @@ while :; do
             no_backups=1
             shift
             ;;
+        settings)
+            do_settings=1
+            shift
+            break
+            ;;
         --)
             shift
             break
@@ -196,5 +220,10 @@ while :; do
             ;;
     esac
 done
+
+if [ "$do_settings" = "1" ]; then
+    run_settings_file "$1"
+    exit $?
+fi
 
 install_dotfiles
